"""Add Date column

Revision ID: 110ed53ea365
Revises: 
Create Date: 2026-02-10 20:20:49.348882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110ed53ea365'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clockin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Date', sa.String(length=100), nullable=True))

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('Password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('sal_req', schema=None) as batch_op:
        batch_op.add_column(sa.Column('I_D', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sal_req', schema=None) as batch_op:
        batch_op.drop_column('I_D')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('Password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('clockin', schema=None) as batch_op:
        batch_op.drop_column('Date')

    # ### end Alembic commands ###
