"""update Status in Sal_req

Revision ID: 382f8355bab6
Revises: 4c4400d97c01
Create Date: 2026-02-18 21:42:40.554407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382f8355bab6'
down_revision = '4c4400d97c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sal_req', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Status', sa.String(length=100), nullable=True))
        batch_op.drop_column('Request')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sal_req', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Request', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('Status')

    # ### end Alembic commands ###
