"""add application_time to Applications

Revision ID: 4c4400d97c01
Revises: 9e35a5458f3d
Create Date: 2026-02-13 16:46:20.755335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4400d97c01'
down_revision = '9e35a5458f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Application_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('Clock_in_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Clock_in_time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('Application_time')

    # ### end Alembic commands ###
