"""Add Date column

Revision ID: 5d3a0b5b2476
Revises: 110ed53ea365
Create Date: 2026-02-11 20:55:07.285834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d3a0b5b2476'
down_revision = '110ed53ea365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clockin', schema=None) as batch_op:
        batch_op.alter_column('Date',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('No_of_clockin', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('No_of_clockin')

    with op.batch_alter_table('clockin', schema=None) as batch_op:
        batch_op.alter_column('Date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
