"""Add Clock_in_time column

Revision ID: 90c4e50ca9d7
Revises: 5d3a0b5b2476
Create Date: 2026-02-11 21:33:56.752788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c4e50ca9d7'
down_revision = '5d3a0b5b2476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clockin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Clock_in_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('Date')
        batch_op.drop_column('Time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clockin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Time', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('Date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('Clock_in_time')

    # ### end Alembic commands ###
