"""add application_time to Applications

Revision ID: 9e35a5458f3d
Revises: 90c4e50ca9d7
Create Date: 2026-02-13 16:25:42.425305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e35a5458f3d'
down_revision = '90c4e50ca9d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Clock_in_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('Time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Time', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('Clock_in_time')

    # ### end Alembic commands ###
