"""update Employee and Transaction in employee.py

Revision ID: b5e522880e56
Revises: 4a525a7cec3d
Create Date: 2026-02-26 18:09:26.929489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e522880e56'
down_revision = '4a525a7cec3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('Salary_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Salary_status', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
