"""initial clean setup

Revision ID: c4349e18fc7a
Revises: 
Create Date: 2026-03-05 00:37:17.685123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4349e18fc7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=True),
    sa.Column('Department', sa.String(length=100), nullable=True),
    sa.Column('Request', sa.String(length=100), nullable=True),
    sa.Column('Duration', sa.String(length=100), nullable=True),
    sa.Column('Application_time', sa.DateTime(), nullable=True),
    sa.Column('Status', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clockin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=True),
    sa.Column('Department', sa.String(length=100), nullable=True),
    sa.Column('Clock_in_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('First_name', sa.String(length=100), nullable=True),
    sa.Column('Last_name', sa.String(length=100), nullable=True),
    sa.Column('Department', sa.String(length=100), nullable=True),
    sa.Column('I_D', sa.String(length=50), nullable=True),
    sa.Column('Gender', sa.String(length=100), nullable=True),
    sa.Column('DOB', sa.String(length=100), nullable=True),
    sa.Column('Phone_Number', sa.String(length=100), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.Column('Nationality', sa.String(length=100), nullable=True),
    sa.Column('State', sa.String(length=100), nullable=True),
    sa.Column('City', sa.String(length=100), nullable=True),
    sa.Column('Address', sa.String(length=100), nullable=True),
    sa.Column('Employment_type', sa.String(length=100), nullable=True),
    sa.Column('Basic_salary', sa.Integer(), nullable=True),
    sa.Column('Salary_Frequency', sa.String(length=100), nullable=True),
    sa.Column('Bank_Name', sa.String(length=100), nullable=True),
    sa.Column('Account_Number', sa.String(length=100), nullable=True),
    sa.Column('Next_of_kin', sa.String(length=100), nullable=True),
    sa.Column('Relationship', sa.String(length=100), nullable=True),
    sa.Column('number', sa.String(length=100), nullable=True),
    sa.Column('addres', sa.String(length=100), nullable=True),
    sa.Column('Username', sa.String(length=100), nullable=True),
    sa.Column('Password', sa.String(length=200), nullable=True),
    sa.Column('No_of_clockin', sa.Integer(), nullable=True),
    sa.Column('Balance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sal_req',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('I_D', sa.String(length=50), nullable=True),
    sa.Column('Name', sa.String(length=100), nullable=True),
    sa.Column('Department', sa.String(length=100), nullable=True),
    sa.Column('Request', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('sal_req')
    op.drop_table('employee')
    op.drop_table('clockin')
    op.drop_table('applications')
    # ### end Alembic commands ###
