"""update Salary_status and Balance in Employee model

Revision ID: e2359231dd0f
Revises: fc26bba05789
Create Date: 2026-02-20 14:11:40.611786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2359231dd0f'
down_revision = 'fc26bba05789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Salary_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('Balance', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('Balance')
        batch_op.drop_column('Salary_status')

    # ### end Alembic commands ###
